# Generated by Django 2.2.3 on 2019-07-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evroclassik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evroclassik.Catalog')),
            ],
            options={
                'verbose_name_plural': 'furnitures',
            },
        ),
    ]
