# Generated by Django 2.2.3 on 2019-07-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evroclassik', '0002_auto_20190721_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='name_furniture',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
